import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:intl/intl.dart';
import '../models/meeting.dart';

/// Service for sharing meeting invitations with participants
class ShareService {
  /// Format meeting details for sharing
  static String formatMeetingInvitation(Meeting meeting) {
    final dateFormat = DateFormat('EEEE, MMMM d, y');
    final timeFormat = DateFormat('h:mm a');

    final startTime = timeFormat.format(meeting.dateTime);
    final endTime = timeFormat.format(meeting.endTime);
    final date = dateFormat.format(meeting.dateTime);

    final buffer = StringBuffer();
    buffer.writeln('═══════════════════════════════');
    buffer.writeln('📅 MEETING INVITATION');
    buffer.writeln('═══════════════════════════════');
    buffer.writeln();
    buffer.writeln('📌 ${meeting.title}');
    buffer.writeln();
    buffer.writeln('📆 Date: $date');
    buffer.writeln('🕐 Time: $startTime - $endTime');
    buffer.writeln('⏱️  Duration: ${meeting.durationMinutes} minutes');

    // Add category
    buffer.writeln('🏷️  Category: ${meeting.category.toUpperCase()}');

    // Add meeting link if available
    if (meeting.meetingLink != null && meeting.meetingLink!.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('🔗 Join Meeting:');
      buffer.writeln(meeting.meetingLink);
    }

    if (meeting.participants.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('👥 Participants:');
      buffer.writeln('   ${meeting.participants.join(", ")}');
    }

    if (meeting.description != null && meeting.description!.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('📝 Description:');
      buffer.writeln(meeting.description);
    }

    buffer.writeln();
    buffer.writeln('───────────────────────────────');
    buffer.writeln('Generated by Meeting Scheduler App');
    buffer.writeln('───────────────────────────────');

    return buffer.toString();
  }

  /// Share meeting via general share sheet (allows user to choose app)
  static Future<void> shareMeeting(Meeting meeting) async {
    final invitation = formatMeetingInvitation(meeting);

    await Share.share(
      invitation,
      subject: 'Meeting Invitation: ${meeting.title}',
    );
  }

  /// Send meeting invitation via email
  static Future<void> shareViaEmail({
    required Meeting meeting,
    required String recipientEmail,
  }) async {
    final invitation = formatMeetingInvitation(meeting);
    final subject = Uri.encodeComponent('Meeting Invitation: ${meeting.title}');
    final body = Uri.encodeComponent(invitation);

    final emailUrl = 'mailto:$recipientEmail?subject=$subject&body=$body';
    final uri = Uri.parse(emailUrl);

    if (await canLaunchUrl(uri)) {
      await launchUrl(uri);
    } else {
      throw 'Could not launch email app';
    }
  }

  /// Send meeting invitation via SMS
  static Future<void> shareViaSMS({
    required Meeting meeting,
    required String phoneNumber,
  }) async {
    final invitation = formatMeetingInvitation(meeting);
    final body = Uri.encodeComponent(invitation);

    final smsUrl = 'sms:$phoneNumber?body=$body';
    final uri = Uri.parse(smsUrl);

    if (await canLaunchUrl(uri)) {
      await launchUrl(uri);
    } else {
      throw 'Could not launch SMS app';
    }
  }

  /// Generate a simple text invitation (for copying)
  static String generateTextInvitation(Meeting meeting) {
    return formatMeetingInvitation(meeting);
  }
}
